<?php
global $vw;
$vh = $vw . 'shared\visitor_header.phtml';
require $vh;
?>


<form class="form-signin">
    <div class="form-label-group">
        <input type="email" id="inputUsername" class="form-control" placeholder="Username" required="" autofocus="">
        <label for="inputEmail">Username</label>
    </div>

    <div class="form-label-group">
        <input type="password" id="inputPassword" class="form-control" placeholder="Password" required="">
        <label for="inputPassword">Password</label>
    </div>

    <div class="checkbox mb-3">
        <label>
            <input type="checkbox" value="remember-me"> Remember me
        </label>
    </div>
</form>s