<?php
    global $vw;
    $vh = $vw . 'shared/admin_header.phtml';
    require $vh;
?>
<main>
    <div class="container">
        <h4 class="custom-content-title"><?php echo $this->title ?></h4>
        <hr>
        <form class="form-category" method="post" action="<?php echo URL;?>category/savesubmit">
            <input type="hidden" name="id" value="<?php echo $this->model['id'] ?>">
            <input type="hidden" name="task" value="<?php echo $this->task ?>">
            <div class="form-group row">
                <label for="categoryTitle" class="text-right col-sm-2 col-form-label">Title</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="categoryTitle" name="title" value="<?php echo $this->model['title'] ?>">
                </div>
            </div>
            <div class="form-group row">
                <label for="categoryDescription" class="text-right col-sm-2 col-form-label">Description</label>
                <div class="col-sm-10">
                    <textarea type="text" class="form-control" id="categoryDescription" name="description"><?php echo $this->model['description'] ?></textarea>
                </div>
            </div>
            <div class="form-group row row">
                <div class="col-sm-10 offset-md-2 ">
                    <button type="submit" class="btn btn-primary"> Save Changes</button>
                    <a class="btn btn-secondary" href="<?php echo URL;?>/category/list"> Cancel</a>
                </div>
            </div>
        </form>
    </div>
</main>