<?php
    global $vw;
    $vh = $vw . 'shared/visitor_header.phtml';
    $cpv = $vw . 'shared/category_partial.phtml';
    $pgn = $vw . 'shared/pagination_partial.phtml';
    require $vh;
    $dm = $this->data_manager;
    $pg = $this->pagination;
    $mo = $this->model;
    $page_number = intVal($pg['page_number']);
    $page_count = intVal($pg['page_count']);
    $total_item = intVal($pg['total_item']);
    $start = (($page_number - 1) * 3) +1;
    $end = ($page_number * 3) > $total_item ? $total_item : ($page_number * 3);
    $list_link = "items";
    $param = [];
    if(isset($_GET['category'])){
        $param[] = "category=" . $_GET['category'];
    }
?>
<main>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <?php require $cpv;?>
            </div>
            <div class="col-md-8">
                <h4 class="custom-content-title">Items</h4>
                <?php if(count($mo)>0):?>
                    <ul class="list-unstyled">
                        <?php for($x =($start-1); $x < $end; $x++): ?>
                            <li class="media my-4">
                                <div class="custom-img-con mr-4 ">
                                    <img src="<?php echo URL . $mo[$x][4];?>" class="img-thumbnail custom-img" alt="<?php echo $mo[$x][1];?>">
                                </div>
                                <div class="media-body">
                                    <a href="<?php echo URL . 'item/info/' . $mo[$x][0];?>">
                                        <h5 class="mt-0 mb-1"><?php echo $mo[$x][1];?></h5>
                                    </a>
                                    <?php echo $mo[$x][2];?>
                                </div>
                            </li>
                        <?php endfor; ?>
                    </ul>
                <?php else:?>
                    <div class="text-center">
                        <h3>No items are listed</h3>
                    </div>
                <?php endif;?>
                <?php if(count($mo)>0):?>
                    <div class="text-right mt-3">
                        <?php require $pgn;?>
                    </div>
                <?php endif;?>
            </div>
        </div>
    </div>
</main>

