<?php
    global $vw;
    $vh = $vw . 'shared/visitor_header.phtml';
    require $vh;
    $mo = $this->model;
    $ca = $this->data_manager->getCategoryById($mo[5]);
?>
<main>
    <div class="container">
        <div class="row mt-3">
            <div class="col-md-8 offset-md-2">
                <h4>Information</h4>
                <div class="card custom-card mb-3">
                    <div class="row no-gutters">
                        <div class="col-md-4">
                            <div class="custom-img-container mt-3 mb-3">
                                <img src="<?php echo URL . $mo[4];?>" class="card-img" alt="<?php echo $mo[1];?>">
                            </div>
                        </div>
                        <div class="col-md-8">
                            <div class="card-body">
                                <h2 class="card-title"><?php echo $mo[1];?></h2>
                                <p class="card-text"><?php echo $mo[2];?></p>
                                <span class="badge badge-pill badge-primary"><?echo $ca[1]?></span>
                                <div class="text-right">
                                    <h4><?php echo "$$mo[3]";?></h4>
                                    <a class="btn btn-primary" href="<? echo URL . 'items'?>">Back</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div> 
        </div>
    </div>
</main>