<?php
    global $vw;
    $vh = $vw . 'shared/visitor_header.phtml';
    $pgn = $vw . 'shared/pagination_partial.phtml';
    require $vh;
    $pg = $this->pagination;
    $mo = $this->model;
    $page_number = intVal($pg['page_number']);
    $page_count = intVal($pg['page_count']);
    $total_item = intVal($pg['total_item']);
    $start = (($page_number - 1) * 3) +1;
    $end = ($page_number * 3) > $total_item ? $total_item : ($page_number * 3);
    $list_link = "/search";
    $param = [];
    print_r($model);
?>
<main>
    <div class="container">
        <div class="row mt-3 mb-3">
            <div class="col-md-8 offset-md-4">
                <form class="form-inline">
                    <div class="input-group mb-2 mr-sm-2 custom-search">
                        <span class="fa fa-search"></span>
                        <input type="text" class="form-control" id="inlineFormInputGroupSearch" placeholder="keyword..." name="keyword" value="<?php echo $this->keyword;?>">
                        <div class="input-group-append">
                            <button type submit class="btn btn-outline-primary" type="button">Go</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="card-deck custom-card">
            <?php foreach($this->model as $key=>$value): ?>
                <div class="card custom-card">
                    <div class="text-center mt-2 mb-2 custom-img-container">
                        <img src="<?php echo URL . $value[4]?>" class="card-img-top img-responsive" alt="<?php echo $value[1]?>">
                    </div>
                    <div class="card-body">
                        <a href="<?php echo URL . 'item/info/' . $value[0];?>">
                            <h5 class="card-title"><?php echo $value[1]?></h5>
                        </a>
                        <p class="card-text"><?php echo $value[2]?></p>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
        <?php if(count($mo)>0):?>
            <div class="text-right mt-3">
                <?php require $pgn;?>
            </div>
        <?php endif;?>
    </div>
</main>