<?php
    global $vw;
    $vh = $vw . 'shared/visitor_header.phtml';
    $pgn = $vw . 'shared/pagination_partial.phtml';
    require $vh;
    $pg = $this->pagination;
    $mo = $this->model;
    $page_number = intVal($pg['page_number']);
    $page_count = intVal($pg['page_count']);
    $total_item = intVal($pg['total_item']);
    $start = (($page_number - 1) * 3) +1;
    $end = ($page_number * 3) > $total_item ? $total_item : ($page_number * 3);
    $list_link = "search";
    $param = [];
    if(isset($_GET['keyword'])){
        $param[] = "keyword=" . $_GET['keyword'];
    }
    $img_root_url = URL;
?>
<main>
    <div class="container">
        <div class="row mt-3 mb-3">
            <div class="col-md-8 offset-md-4">
                <form class="form-inline">
                    <div class="input-group mb-2 mr-sm-2 custom-search">
                        <span class="fa fa-search"></span>
                        <input type="text" class="form-control" id="inlineFormInputGroupSearch" placeholder="keyword..." name="keyword" value="<?php echo $this->keyword;?>">
                        <div class="input-group-append">
                            <button type submit class="btn btn-outline-primary" type="button">Go</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <?php if(count($this->model)>0 && $this->keyword !=""):?>
            <div class="card-deck custom-card">
                <?php for($x =($start-1); $x < $end; $x++): ?>
                    <div class="card custom-card">
                        <div class="text-center mt-2 mb-2 custom-img-container">
                            <img src="<?php echo $img_root_url . $mo[$x][4]?>" class="card-img-top img-responsive" alt="<?php echo $mo[$x][1]?>">
                        </div>
                        <div class="card-body">
                            <a href="<?php echo URL . 'item/info/' . $mo[$x][0];?>">
                                <h5 class="card-title"><?php echo $mo[$x][1]?></h5>
                            </a>
                            <p class="card-text"><?php echo $mo[$x][2]?></p>
                        </div>
                    </div>
                <?php endfor; ?>
            </div>
        <?php elseif($this->keyword !=""):?>
            <div class="text-center">
                <h5>No items are listed</h5>
            </div>
        <?php endif;?>
        <?php if(count($mo)>0):?>
            <div class="text-right mt-3">
                <?php require $pgn;?>
            </div>
        <?php endif;?>
    </div>
</main>